# Setup
name: XIVAPP
description: Where the community comes to play!
baseurl: "https://ffxivapp.github.io/xivapp.com/"
locale: "en-US"
theme: jekyll-theme-architect

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
