# Setup
name: XIVAPP
description: Where the community comes to play!
baseurl: ""
locale: "en-US"
theme: Architect

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect